# Definition of global variables (all stages)
variables:
  PYTHONUNBUFFERED: "1"
  CONDA_ROOT: "${CI_PROJECT_DIR}/miniconda"


# Definition of our build pipeline order
stages:
  - build
  - deploy
  - pypi


# Build targets
.build_template:
  stage: build
  script:
    - python3 ./bob/devtools/bootstrap.py -vv build
    - source ${CONDA_ROOT}/etc/profile.d/conda.sh
    - conda activate base
    - python3 ./bob/devtools/build.py -vv
  artifacts:
    expire_in: 1 week
  cache:
    paths:
      - miniconda.sh
      - ${CONDA_ROOT}/pkgs/*.tar.bz2
      - ${CONDA_ROOT}/pkgs/urls.txt


.build_linux_template:
  extends: .build_template
  tags:
    - docker
  image: continuumio/conda-concourse-ci
  artifacts:
    paths:
      - ${CONDA_ROOT}/conda-bld/linux-64/*.tar.bz2
      - ${CONDA_ROOT}/conda-bld/noarch/*.tar.bz2
  cache:
    key: "linux-cache"


.build_macosx_template:
  extends: .build_template
  tags:
    - macosx
  artifacts:
    paths:
      - ${CONDA_ROOT}/conda-bld/osx-64/*.tar.bz2
      - ${CONDA_ROOT}/conda-bld/noarch/*.tar.bz2
  cache:
    key: "macosx-cache"


build_linux_36:
  extends: .build_linux_template
  variables:
    PYTHON_VERSION: "3.6"

build_linux_37:
  extends: .build_linux_template
  variables:
    PYTHON_VERSION: "3.7"
    BUILD_EGG: "true"
  script:
    - python3 ./bob/devtools/bootstrap.py -vv build
    - source ${CONDA_ROOT}/etc/profile.d/conda.sh
    - conda activate base
    - python3 ./bob/devtools/build.py -vv --twine-check
  artifacts:
    paths:
      - dist/*.zip
      - sphinx
      - ${CONDA_ROOT}/conda-bld/linux-64/*.tar.bz2
      - ${CONDA_ROOT}/conda-bld/noarch/*.tar.bz2

build_macosx_36:
  extends: .build_macosx_template
  variables:
    PYTHON_VERSION: "3.6"


build_macosx_37:
  extends: .build_macosx_template
  variables:
    PYTHON_VERSION: "3.7"


# Deploy targets
.deploy_template:
  stage: deploy
  script:
    - python3 ./bob/devtools/bootstrap.py -vv local base
    - source ${CONDA_ROOT}/etc/profile.d/conda.sh
    - conda activate base
    - bdt ci base-deploy -vv
    - bdt ci deploy -vv
    - bdt ci clean -vv
  dependencies:
    - build_linux_36
    - build_linux_37
    - build_macosx_36
    - build_macosx_37
  tags:
    - docker
  cache:
    paths:
      - miniconda.sh
      - ${CONDA_ROOT}/pkgs/*.tar.bz2
      - ${CONDA_ROOT}/pkgs/urls.txt


deploy_beta:
  extends: .deploy_template
  environment: beta
  only:
    - master


deploy_stable:
  extends: .deploy_template
  environment: stable
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
  except:
    - branches


pypi:
  stage: pypi
  environment: pypi
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
  except:
    - branches
  script:
    - python3 ./bob/devtools/bootstrap.py -vv local base
    - source ${CONDA_ROOT}/etc/profile.d/conda.sh
    - conda activate base
    - bdt ci pypi -vv dist/*.zip
    - bdt ci clean -vv
  dependencies:
    - build_linux_36
    - build_linux_37
    - build_macosx_36
    - build_macosx_37
  tags:
    - docker
  cache:
    paths:
      - miniconda.sh
      - ${CONDA_ROOT}/pkgs/*.tar.bz2
      - ${CONDA_ROOT}/pkgs/urls.txt
