{% set name = "python-gitlab" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a862c6874524ab585b725a17b2cd2950fc09d6d74205f40a11be2a4e8f2dcaa1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
  entry_points:
    - gitlab = gitlab.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6.0
    - requests >=2.22.0
    - requests-toolbelt >=0.9.1

test:
  imports:
    - gitlab
  commands:
    - gitlab -h

about:
  home: https://github.com/python-gitlab/python-gitlab
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: 'Python wrapper for the GitLab API'
  description: |
    python-gitlab is a Python package providing access to the GitLab
    server API. It supports the v4 API of GitLab, and provides a CLI
    tool (gitlab).
  doc_url: https://python-gitlab.readthedocs.io/
  dev_url: https://github.com/python-gitlab/python-gitlab

extra:
  recipe-maintainers:
    - anjos
