{% set name = "python-gitlab" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71445d7444fe3354bf90a52d6249f91c9e572a8ef6c143afd9de25f50c92d499

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
  entry_points:
    - gitlab = gitlab.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6.0
    - requests >=2.22.0

test:
  imports:
    - gitlab
  commands:
    - gitlab -h

about:
  home: https://github.com/python-gitlab/python-gitlab
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: 'Python wrapper for the GitLab API'
  description: |
    python-gitlab is a Python package providing access to the GitLab
    server API. It supports the v4 API of GitLab, and provides a CLI
    tool (gitlab).
  doc_url: https://python-gitlab.readthedocs.io/
  dev_url: https://github.com/python-gitlab/python-gitlab

extra:
  recipe-maintainers:
    - anjos
