{% set version = "1.3.1" %}

package:
  name: docformatter
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/myint/docformatter

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."

requirements:
  build:
    - python
    - pip

  run:
    - python
    - untokenize

test:

  source_files:
    - test_docformatter.py
    - docformatter.py

  requires:
    - nose

  commands:
    - nosetests -sv test_docformatter.py

about:
  home: https://github.com/myint/docformatter
  license: MIT License
  license_family: MIT
  summary: 'Formats docstrings to follow PEP 257'

extra:
  recipe-maintainers:
    - anjos
