{% set name = 'bob.devtools' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
    - bdt = bob.devtools.scripts.bdt:main
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt
    # installs the documentation source, readme to share/doc so it is available
    # during test time
    - install -d "${PREFIX}/share/doc/{{ name }}"
    - cp -R README.rst doc "${PREFIX}/share/doc/{{ name }}/"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
  run:
    - python
    - setuptools
    - click >=7
    - click-plugins
    - conda=4
    - conda-build=3.16
    - conda-verify=3
    - certifi
    - pytz
    - python-dateutil
    - gitpython
    - python-gitlab
    - requests
    - sphinx
    - pyyaml
    - twine
    - lxml
    - jinja2
    - termcolor

test:
  requires:
    - sphinx_rtd_theme
  imports:
    - {{ name }}
  commands:
    - bdt -h
    - bdt -?
    - bdt --help
    - bdt lasttag --help
      #- bdt lasttag -vv bob/bob.devtools
    - bdt commitfile --help
    - bdt changelog --help
      #- bdt changelog -vv bob/bob.devtools changelog.md
    - bdt release --help
      #- bdt release -vvd changelog.md
    - bdt visibility --help
      #- bdt visibility -vv bob/bob.devtools
    - bdt dumpsphinx --help
    - bdt dumpsphinx https://docs.python.org/3/objects.inv > /dev/null
    - bdt create --help
    - bdt build --help
    - bdt test --help
    - bdt getpath --help
      #- bdt getpath -vv bob/bob.devtools .gitignore
    - bdt caupdate --help
    - bdt new --help
    - bdt new -t "New package" -o bob.foobar bob/bob.foobar "John Doe" "joe.doe@example.com"
    - bdt new -t "New package" -l bsd -o bob.foobar2 bob/bob.foobar "John Doe" "joe.doe@example.com"
    - bdt new -t "New package" -l bsd -o beat.foobar beat/beat.foobar "John Doe" "joe.doe@example.com"
    - bdt ci --help
    - bdt ci base-build --help
    - bdt ci build --help
    - bdt ci base-deploy --help
    - bdt ci deploy --help
    - bdt ci pypi --help
    - bdt ci readme --help
    - bdt ci clean --help
    - sphinx-build -aEW ${PREFIX}/share/doc/{{ name }}/doc {{ project_dir }}/sphinx

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Tools for development and CI integration of Bob packages
  license_family: BSD
  license_file: ../LICENSE
